version: '3.8'

services:
  backend:
    build: ./python-engine
    container_name: kpi-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG=false
      - ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://localhost:8082,http://135.125.103.119:8082,http://135.125.103.119
    networks:
      - kpi-network

  frontend:
    build: ./electron-app
    container_name: kpi-frontend
    restart: unless-stopped
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - kpi-network

networks:
  kpi-network:
    driver: bridge

volumes:
  data:
